[package]
name = "harness-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
pulldown-cmark.workspace = true
ratatui.workspace = true
similar.workspace = true
syntect.workspace = true
unicode-width.workspace = true
